# ShopSum

## Privacy Policy

ShopSum does not collect, store, or process any of your personal information. All data generated by the app is securely stored locally on your device.

Additionally, ShopSum does not use third-party analytics tools or display advertisements within the app.

By using ShopSum, you can trust that your data remains private and under your control.
